{
    "links": {
        "decline": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/decline"
        },
        "approve": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/approve"
        },
        "html": {
            "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
        },
        "activity": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/activity"
        },
        "self": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
        },
        "commits": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/commits"
        },
        "merge": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/merge"
        },
        "statuses": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/statuses"
        },
        "comments": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments"
        },
        "diff": {
            "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/diff"
        }
    },
    "task_count": 0,
    "source": {
        "repository": {
            "full_name": "chummels/yt",
            "uuid": "{cc72b7fe-3d37-4cd2-a367-f2de113a2e82}",
            "type": "repository",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/chummels/yt"
                },
                "html": {
                    "href": "https://bitbucket.org/chummels/yt"
                },
                "avatar": {
                    "href": "https://bitbucket.org/chummels/yt/avatar/32/"
                }
            },
            "name": "yt"
        },
        "commit": {
            "hash": "3ffe6d5372f8",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/chummels/yt/commit/3ffe6d5372f8"
                }
            }
        },
        "branch": {
            "name": "yt-3.0"
        }
    },
    "closed_by": {
        "username": "chummels",
        "type": "user",
        "links": {
            "self": {
                "href": "https://api.bitbucket.org/2.0/users/chummels"
            },
            "html": {
                "href": "https://bitbucket.org/chummels/"
            },
            "avatar": {
                "href": "https://bitbucket.org/account/chummels/avatar/32/"
            }
        },
        "display_name": "chummels",
        "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
    },
    "title": "Adding error message when trying to run yt without having run setup.py for this version",
    "id": 911,
    "comment_count": 24,
    "created_on": "2014-05-19T21:16:37.005322+00:00",
    "merge_commit": null,
    "comments": [
        {
            "content": {
                "markup": "markdown",
                "raw": "`YT_DEST` will only be set if you installed using the install script.  Can you rephrase this to be more general?",
                "html": "<p><code>YT_DEST</code> will only be set if you installed using the install script.  Can you rephrase this to be more general?</p>"
            },
            "user": {
                "username": "ngoldbaum",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/ngoldbaum"
                    },
                    "html": {
                        "href": "https://bitbucket.org/ngoldbaum/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/ngoldbaum/avatar/32/"
                    }
                },
                "display_name": "Nathan Goldbaum",
                "uuid": "{5dcd72da-6420-4a6d-9571-e75dffcac587}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917028"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917028"
                },
                "code": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/diff/chummels/yt:4cafede7f67b..ee9a8bb2ae6e?path=yt%2Futilities%2Fexceptions.py"
                }
            },
            "created_on": "2014-05-19T21:18:21.464211+00:00",
            "updated_on": "2014-05-19T21:18:21.472409+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "inline": {
                "to": 385,
                "path": "yt/utilities/exceptions.py",
                "from": null
            },
            "type": "pullrequest_comment",
            "id": 1917028
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "Can you reraise the information in the ImportError?  I'd specifically like to see the original traceback, if possible.\n\nThe way this is written right now will make it difficult to see where the ImportError actually happened if the error was unrelated to setup.py not being run correctly.  That might happen if I make a mistake during development, for example.",
                "html": "<p>Can you reraise the information in the ImportError?  I'd specifically like to see the original traceback, if possible.</p>\n<p>The way this is written right now will make it difficult to see where the ImportError actually happened if the error was unrelated to setup.py not being run correctly.  That might happen if I make a mistake during development, for example.</p>"
            },
            "user": {
                "username": "ngoldbaum",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/ngoldbaum"
                    },
                    "html": {
                        "href": "https://bitbucket.org/ngoldbaum/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/ngoldbaum/avatar/32/"
                    }
                },
                "display_name": "Nathan Goldbaum",
                "uuid": "{5dcd72da-6420-4a6d-9571-e75dffcac587}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917126"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917126"
                },
                "code": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/diff/chummels/yt:3ffe6d5372f8..ea182fc68fae?path=yt%2F__init__.py"
                }
            },
            "created_on": "2014-05-19T21:29:01.301706+00:00",
            "updated_on": "2014-05-19T21:29:22.174345+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "inline": {
                "to": 118,
                "path": "yt/__init__.py",
                "from": null
            },
            "type": "pullrequest_comment",
            "id": 1917126
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "Yeah, I considered that.  I'll edit to take this into account.",
                "html": "<p>Yeah, I considered that.  I'll edit to take this into account.</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917126"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917126"
                    }
                },
                "id": 1917126
            },
            "created_on": "2014-05-19T21:29:53.452912+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917137"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917137"
                },
                "code": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/diff/chummels/yt:None..None?path=yt%2F__init__.py"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "inline": {
                "to": null,
                "path": "yt/__init__.py",
                "from": null
            },
            "type": "pullrequest_comment",
            "id": 1917137,
            "updated_on": "2014-05-19T21:29:53.465034+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "All tests pass. Good job!",
                "html": "<p>All tests pass. Good job!</p>"
            },
            "user": {
                "username": "yt-fido",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/yt-fido"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt-fido/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/yt-fido/avatar/32/"
                    }
                },
                "display_name": "yt-fido",
                "uuid": "{da2aa332-3f05-45c9-ae53-ff5ba34b35ce}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917261"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917261"
                }
            },
            "created_on": "2014-05-19T21:47:25.827680+00:00",
            "updated_on": "2014-05-19T21:47:25.958967+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917261
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "Hmm, I'm not sure that we should be trying to catch this error, especially using a big try/except over so many modules.",
                "html": "<p>Hmm, I'm not sure that we should be trying to catch this error, especially using a big try/except over so many modules.</p>"
            },
            "user": {
                "username": "samskillman",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/samskillman"
                    },
                    "html": {
                        "href": "https://bitbucket.org/samskillman/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/samskillman/avatar/32/"
                    }
                },
                "display_name": "Sam Skillman",
                "uuid": "{b03f9d96-1c52-4f21-bbdc-72f8e2a97a81}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917331"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917331"
                }
            },
            "created_on": "2014-05-19T21:57:10.656561+00:00",
            "updated_on": "2014-05-19T21:57:10.665606+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917331
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I agree. I think this needs further thought.",
                "html": "<p>I agree. I think this needs further thought.</p>"
            },
            "user": {
                "username": "MatthewTurk",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/MatthewTurk"
                    },
                    "html": {
                        "href": "https://bitbucket.org/MatthewTurk/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/MatthewTurk/avatar/32/"
                    }
                },
                "display_name": "Matt Turk",
                "uuid": "{b3f0b280-55fc-4e8a-8bd1-40478d4cbdbf}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917331"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917331"
                    }
                },
                "id": 1917331
            },
            "created_on": "2014-05-19T22:05:07.457099+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917381"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917381"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917381,
            "updated_on": "2014-05-19T22:05:07.477897+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I'm open to just catching the first import failure if that seems more targetted, but I think having an error with a helpful message raised to the user is a good idea in general.  We're used to seeing the error and know how to fix it, but the average joe user doesn't know what this means.",
                "html": "<p>I'm open to just catching the first import failure if that seems more targetted, but I think having an error with a helpful message raised to the user is a good idea in general.  We're used to seeing the error and know how to fix it, but the average joe user doesn't know what this means.</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917417"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917417"
                }
            },
            "created_on": "2014-05-19T22:13:31.821393+00:00",
            "updated_on": "2014-05-19T22:13:31.829341+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917417
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "What do you think about incorporating Nathan's suggestion where the exception still passes its import failure to the user, and I just put the try: except around the first import (since that is the first one that fails when yt isn't setup properly)?",
                "html": "<p>What do you think about incorporating Nathan's suggestion where the exception still passes its import failure to the user, and I just put the try: except around the first import (since that is the first one that fails when yt isn't setup properly)?</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917422"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917422"
                }
            },
            "created_on": "2014-05-19T22:14:38.182173+00:00",
            "updated_on": "2014-05-19T22:14:38.190988+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917422
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I guess I'm just -1 on pushing the error deeper into the stack. We should emphasize that people shouldn't use the same directory for 2.x and 3.0. That makes the error traceback much simpler to just figure out.",
                "html": "<p>I guess I'm just -1 on pushing the error deeper into the stack. We should emphasize that people shouldn't use the same directory for 2.x and 3.0. That makes the error traceback much simpler to just figure out.</p>"
            },
            "user": {
                "username": "samskillman",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/samskillman"
                    },
                    "html": {
                        "href": "https://bitbucket.org/samskillman/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/samskillman/avatar/32/"
                    }
                },
                "display_name": "Sam Skillman",
                "uuid": "{b03f9d96-1c52-4f21-bbdc-72f8e2a97a81}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917422"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917422"
                    }
                },
                "id": 1917422
            },
            "created_on": "2014-05-19T22:25:10.093753+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917494"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917494"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917494,
            "updated_on": "2014-05-19T22:25:10.100528+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "You think people should have separate installs for the different versions of yt that are both found in the same repository?  I think I'm -1 on that.  I thought the whole point of merging everything into the same repo (yt 2.x and yt 3.0) was to enable the code to be more consolidated, and potentially easier to swap between the two.\n\nI'm only pushing the error 1 deeper into the stack, and I'm just including a yt specific exception with a helpful error message.  I didn't think this would be that controversial.",
                "html": "<p>You think people should have separate installs for the different versions of yt that are both found in the same repository?  I think I'm -1 on that.  I thought the whole point of merging everything into the same repo (yt 2.x and yt 3.0) was to enable the code to be more consolidated, and potentially easier to swap between the two.</p>\n<p>I'm only pushing the error 1 deeper into the stack, and I'm just including a yt specific exception with a helpful error message.  I didn't think this would be that controversial.</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917521"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917521"
                }
            },
            "created_on": "2014-05-19T22:28:40.684403+00:00",
            "updated_on": "2014-05-19T22:28:40.691636+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917521
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I have two different directories: yt-hg/ and yt-3.0/, not two different installations. When one fails, the first this i notice is the traceback is looking at the wrong dir, and I fix it.\n",
                "html": "<p>I have two different directories: yt-hg/ and yt-3.0/, not two different installations. When one fails, the first this i notice is the traceback is looking at the wrong dir, and I fix it.</p>"
            },
            "user": {
                "username": "samskillman",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/samskillman"
                    },
                    "html": {
                        "href": "https://bitbucket.org/samskillman/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/samskillman/avatar/32/"
                    }
                },
                "display_name": "Sam Skillman",
                "uuid": "{b03f9d96-1c52-4f21-bbdc-72f8e2a97a81}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917521"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917521"
                    }
                },
                "id": 1917521
            },
            "created_on": "2014-05-19T22:30:47.137298+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917535"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917535"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1917535,
            "updated_on": "2014-05-19T22:30:47.146068+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "Interesting.  But that means you have two copies of the repository, right?  And you just keep one on the yt head and the other on the yt-3.0 head?  I guess that does fix the issue of not knowing which has not had \"setup.py\" run on it, but it seems like just having a single one is probably simpler for most users. Hmm...\n\nSo are people just totally against having this error message?  I'm just trying to make things more intuitive and helpful for everyone.",
                "html": "<p>Interesting.  But that means you have two copies of the repository, right?  And you just keep one on the yt head and the other on the yt-3.0 head?  I guess that does fix the issue of not knowing which has not had \"setup.py\" run on it, but it seems like just having a single one is probably simpler for most users. Hmm...</p>\n<p>So are people just totally against having this error message?  I'm just trying to make things more intuitive and helpful for everyone.</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917535"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917535"
                    }
                },
                "id": 1917535
            },
            "created_on": "2014-05-19T23:46:03.677933+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1918006"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1918006"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1918006,
            "updated_on": "2014-05-19T23:46:03.685400+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I'm just against detecting the error through attempting to import.",
                "html": "<p>I'm just against detecting the error through attempting to import.</p>"
            },
            "user": {
                "username": "samskillman",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/samskillman"
                    },
                    "html": {
                        "href": "https://bitbucket.org/samskillman/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/samskillman/avatar/32/"
                    }
                },
                "display_name": "Sam Skillman",
                "uuid": "{b03f9d96-1c52-4f21-bbdc-72f8e2a97a81}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1918006"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1918006"
                    }
                },
                "id": 1918006
            },
            "created_on": "2014-05-19T23:47:44.747109+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1918013"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1918013"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1918013,
            "updated_on": "2014-05-19T23:47:44.754899+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I wonder if there is a different way of detecting the error.  I just grabbed the first place it errored on the \"import yt\" traceback and wrapped it with the exception check, but if there is a better way, I'm happy to do that.  I just don't know of any other way.",
                "html": "<p>I wonder if there is a different way of detecting the error.  I just grabbed the first place it errored on the \"import yt\" traceback and wrapped it with the exception check, but if there is a better way, I'm happy to do that.  I just don't know of any other way.</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1918013"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1918013"
                    }
                },
                "id": 1918013
            },
            "created_on": "2014-05-19T23:50:16.807746+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1918023"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1918023"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1918023,
            "updated_on": "2014-05-19T23:50:16.816352+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "For what it's worth, I only have one repo, and i manage switching back and forth by doing `hg up yt-3.0` or `hg up yt`, and then `setup.py develop`.  I don't normally forget the `setup.py` step but I do see why that might be confusing to someone who is not used to dealing with python packages.\n\nIn general I more or less agree with Sam and Matt that it's best to not think too much for a user and just let the error propagate as it normally would.  This allows a more experienced user to diagnose the issue and allows us to figure out what went wrong more easily if they contact the mailing list.  Another thing to think about is that `yt update` already manages this workflow in a more user-friendly manner.\n\nOne other issue is that this sort of error indirection can actually make it *more* difficult to debug stuff, particularly if you are accidentally catching errors unrelated to not running `setup.py`.  I alluded to this below, but after further reflection I don't think it's even worth implementing my suggestion - best to not catch the error at all.\n\nReally, this is an education/documentation problem.  We need to make sure that the process of updating the code is clearly stated and that includes executing the setup script.",
                "html": "<p>For what it's worth, I only have one repo, and i manage switching back and forth by doing <code>hg up yt-3.0</code> or <code>hg up yt</code>, and then <code>setup.py develop</code>.  I don't normally forget the <code>setup.py</code> step but I do see why that might be confusing to someone who is not used to dealing with python packages.</p>\n<p>In general I more or less agree with Sam and Matt that it's best to not think too much for a user and just let the error propagate as it normally would.  This allows a more experienced user to diagnose the issue and allows us to figure out what went wrong more easily if they contact the mailing list.  Another thing to think about is that <code>yt update</code> already manages this workflow in a more user-friendly manner.</p>\n<p>One other issue is that this sort of error indirection can actually make it <em>more</em> difficult to debug stuff, particularly if you are accidentally catching errors unrelated to not running <code>setup.py</code>.  I alluded to this below, but after further reflection I don't think it's even worth implementing my suggestion - best to not catch the error at all.</p>\n<p>Really, this is an education/documentation problem.  We need to make sure that the process of updating the code is clearly stated and that includes executing the setup script.</p>"
            },
            "user": {
                "username": "ngoldbaum",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/ngoldbaum"
                    },
                    "html": {
                        "href": "https://bitbucket.org/ngoldbaum/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/ngoldbaum/avatar/32/"
                    }
                },
                "display_name": "Nathan Goldbaum",
                "uuid": "{5dcd72da-6420-4a6d-9571-e75dffcac587}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1917521"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1917521"
                    }
                },
                "id": 1917521
            },
            "created_on": "2014-05-19T23:53:24.376882+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1918036"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1918036"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1918036,
            "updated_on": "2014-05-19T23:53:24.384274+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I think that very simple solution would be to:\n\n1. make `python setup.py develop` spit hidden file into *yt* directory, that would store current `__version__`\n1. in `yt/__init__.py`, **if** that file exists, compare current `__version__` with the file contents and act accordingly\n\n*UPDATE*: In principle we could store additional data there too, like revision used for build/develop etc. That would come handy in bug reports.",
                "html": "<p>I think that very simple solution would be to:</p>\n<ol>\n<li>make <code>python setup.py develop</code> spit hidden file into <em>yt</em> directory, that would store current <code>__version__</code></li>\n<li>in <code>yt/__init__.py</code>, <strong>if</strong> that file exists, compare current <code>__version__</code> with the file contents and act accordingly</li>\n</ol>\n<p><em>UPDATE</em>: In principle we could store additional data there too, like revision used for build/develop etc. That would come handy in bug reports.</p>"
            },
            "user": {
                "username": "xarthisius",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/xarthisius"
                    },
                    "html": {
                        "href": "https://bitbucket.org/xarthisius/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/xarthisius/avatar/32/"
                    }
                },
                "display_name": "Kacper Kowalik",
                "uuid": "{26af8f1d-35b3-46ce-9939-09915b06e31f}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1922164"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1922164"
                }
            },
            "created_on": "2014-05-20T11:19:44.095493+00:00",
            "updated_on": "2014-05-20T11:22:42.218466+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1922164
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "Interesting idea, Kacper.  This would work, and the check in __init__.py would occur prior to any failed imports, so it would alleviate the problems others have alluded to above.  @MatthewTurk @samskillman and @ngoldbaum what do you guys think of this idea?  If there is consensus, I'd be happy to code it up.",
                "html": "<p>Interesting idea, Kacper.  This would work, and the check in <strong>init</strong>.py would occur prior to any failed imports, so it would alleviate the problems others have alluded to above.  <a href=\"/MatthewTurk/\" rel=\"nofollow\" title=\"@MatthewTurk\" class=\"mention\">Matt Turk</a> <a href=\"/samskillman/\" rel=\"nofollow\" title=\"@samskillman\" class=\"mention\">Sam Skillman</a> and <a href=\"/ngoldbaum/\" rel=\"nofollow\" title=\"@ngoldbaum\" class=\"mention\">Nathan Goldbaum</a> what do you guys think of this idea?  If there is consensus, I'd be happy to code it up.</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1922164"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1922164"
                    }
                },
                "id": 1922164
            },
            "created_on": "2014-05-20T19:04:59.250876+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1927658"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1927658"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1927658,
            "updated_on": "2014-05-20T19:04:59.277869+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I think this would work.  I'm still really reluctant to put code solutions in that solve this problem.",
                "html": "<p>I think this would work.  I'm still really reluctant to put code solutions in that solve this problem.</p>"
            },
            "user": {
                "username": "MatthewTurk",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/MatthewTurk"
                    },
                    "html": {
                        "href": "https://bitbucket.org/MatthewTurk/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/MatthewTurk/avatar/32/"
                    }
                },
                "display_name": "Matt Turk",
                "uuid": "{b3f0b280-55fc-4e8a-8bd1-40478d4cbdbf}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1927658"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1927658"
                    }
                },
                "id": 1927658
            },
            "created_on": "2014-05-21T11:57:38.802090+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/1934018"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-1934018"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 1934018,
            "updated_on": "2014-05-21T11:57:38.810288+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "All tests pass. Good job!",
                "html": "<p>All tests pass. Good job!</p>"
            },
            "user": {
                "username": "yt-fido",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/yt-fido"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt-fido/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/yt-fido/avatar/32/"
                    }
                },
                "display_name": "yt-fido",
                "uuid": "{da2aa332-3f05-45c9-ae53-ff5ba34b35ce}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/2018286"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-2018286"
                }
            },
            "created_on": "2014-05-31T17:49:35.397824+00:00",
            "updated_on": "2014-05-31T17:49:35.509428+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 2018286
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "I'm still feeling kind of -1 about this.  I have left some comments for suggestions below, but I'm not sure that we need to develop a technical solution to this problem.",
                "html": "<p>I'm still feeling kind of -1 about this.  I have left some comments for suggestions below, but I'm not sure that we need to develop a technical solution to this problem.</p>"
            },
            "user": {
                "username": "MatthewTurk",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/MatthewTurk"
                    },
                    "html": {
                        "href": "https://bitbucket.org/MatthewTurk/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/MatthewTurk/avatar/32/"
                    }
                },
                "display_name": "Matt Turk",
                "uuid": "{b3f0b280-55fc-4e8a-8bd1-40478d4cbdbf}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/2055221"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-2055221"
                }
            },
            "created_on": "2014-06-05T00:06:32.600123+00:00",
            "updated_on": "2014-06-05T00:06:32.607323+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 2055221
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "Indenting this entire block is probably not necessary.  If `yt.fields.api` is the problem (I don't think it is, if the failure shows up in a Cython module that hasn't been rebuilt) then you could try importing the `yt.fields.api` inside a block and then importing the rest if it works.",
                "html": "<p>Indenting this entire block is probably not necessary.  If <code>yt.fields.api</code> is the problem (I don't think it is, if the failure shows up in a Cython module that hasn't been rebuilt) then you could try importing the <code>yt.fields.api</code> inside a block and then importing the rest if it works.</p>"
            },
            "user": {
                "username": "MatthewTurk",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/MatthewTurk"
                    },
                    "html": {
                        "href": "https://bitbucket.org/MatthewTurk/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/MatthewTurk/avatar/32/"
                    }
                },
                "display_name": "Matt Turk",
                "uuid": "{b3f0b280-55fc-4e8a-8bd1-40478d4cbdbf}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/2055227"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-2055227"
                },
                "code": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/diff/chummels/yt:3ffe6d5372f8..ea182fc68fae?path=yt%2F__init__.py"
                }
            },
            "created_on": "2014-06-05T00:07:32.348044+00:00",
            "updated_on": "2014-06-05T00:07:32.354322+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "inline": {
                "to": null,
                "path": "yt/__init__.py",
                "from": 103
            },
            "type": "pullrequest_comment",
            "id": 2055227
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "This is not necessarily true, though.  If there is a syntax error in `yt.fields` or one of its submodules, it won't be solved by this solution.",
                "html": "<p>This is not necessarily true, though.  If there is a syntax error in <code>yt.fields</code> or one of its submodules, it won't be solved by this solution.</p>"
            },
            "user": {
                "username": "MatthewTurk",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/MatthewTurk"
                    },
                    "html": {
                        "href": "https://bitbucket.org/MatthewTurk/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/MatthewTurk/avatar/32/"
                    }
                },
                "display_name": "Matt Turk",
                "uuid": "{b3f0b280-55fc-4e8a-8bd1-40478d4cbdbf}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/2055232"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-2055232"
                },
                "code": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/diff/chummels/yt:3ffe6d5372f8..ea182fc68fae?path=yt%2Futilities%2Fexceptions.py"
                }
            },
            "created_on": "2014-06-05T00:08:19.170387+00:00",
            "updated_on": "2014-06-05T00:08:19.177084+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "inline": {
                "to": 392,
                "path": "yt/utilities/exceptions.py",
                "from": null
            },
            "type": "pullrequest_comment",
            "id": 2055232
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "And, not everyone will be using it from a `develop` environment.",
                "html": "<p>And, not everyone will be using it from a <code>develop</code> environment.</p>"
            },
            "user": {
                "username": "MatthewTurk",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/MatthewTurk"
                    },
                    "html": {
                        "href": "https://bitbucket.org/MatthewTurk/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/MatthewTurk/avatar/32/"
                    }
                },
                "display_name": "Matt Turk",
                "uuid": "{b3f0b280-55fc-4e8a-8bd1-40478d4cbdbf}"
            },
            "parent": {
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/2055232"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-2055232"
                    }
                },
                "id": 2055232
            },
            "created_on": "2014-06-05T00:08:29.108749+00:00",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/2055233"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-2055233"
                },
                "code": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/diff/chummels/yt:None..None?path=yt%2Futilities%2Fexceptions.py"
                }
            },
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "inline": {
                "to": null,
                "path": "yt/utilities/exceptions.py",
                "from": null
            },
            "type": "pullrequest_comment",
            "id": 2055233,
            "updated_on": "2014-06-05T00:08:29.115553+00:00"
        },
        {
            "content": {
                "markup": "markdown",
                "raw": "There doesn't appear to be much support for this, so I'm declining it.",
                "html": "<p>There doesn't appear to be much support for this, so I'm declining it.</p>"
            },
            "user": {
                "username": "chummels",
                "type": "user",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/users/chummels"
                    },
                    "html": {
                        "href": "https://bitbucket.org/chummels/"
                    },
                    "avatar": {
                        "href": "https://bitbucket.org/account/chummels/avatar/32/"
                    }
                },
                "display_name": "chummels",
                "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
            },
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911/comments/2139157"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911/_/diff#comment-2139157"
                }
            },
            "created_on": "2014-06-13T23:22:09.120940+00:00",
            "updated_on": "2014-06-13T23:22:09.127652+00:00",
            "pullrequest": {
                "type": "pullrequest",
                "links": {
                    "self": {
                        "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/pullrequests/911"
                    },
                    "html": {
                        "href": "https://bitbucket.org/yt_analysis/yt/pull-requests/911"
                    }
                },
                "title": "Adding error message when trying to run yt without having run setup.py for this version",
                "id": 911
            },
            "type": "pullrequest_comment",
            "id": 2139157
        }
    ],
    "reason": "No support for this solution.",
    "type": "pullrequest",
    "close_source_branch": false,
    "state": "DECLINED",
    "description": "I know a common mistake I make (and I assume there are others who do this too) is to switch versions of yt with an \"hg up yt-3.0\" or \"hg up yt\", and then forgetting to run \"python setup.py develop\" prior to trying to use yt.  Inevitably, this yields an error, which is somewhat opaque and may be non-intuitive for new users.\r\n\r\nSo I added a new import exception which returns a helpful message to the user when they are unable to import the default packages (when trying to \"import yt\" in a python session, or running yt from the command line).  The helpful message tells the user how to run setup.py to fix the problem.\r\n\r\nI *think* this is the main reason this exception would be raised, but if I'm being too general here, please let me know how to fix it.",
    "author": {
        "username": "chummels",
        "type": "user",
        "links": {
            "self": {
                "href": "https://api.bitbucket.org/2.0/users/chummels"
            },
            "html": {
                "href": "https://bitbucket.org/chummels/"
            },
            "avatar": {
                "href": "https://bitbucket.org/account/chummels/avatar/32/"
            }
        },
        "display_name": "chummels",
        "uuid": "{de871bb8-32e9-450a-b8c9-2b49a1334f16}"
    },
    "updated_on": "2014-06-13T23:22:21.637260+00:00",
    "destination": {
        "repository": {
            "full_name": "yt_analysis/yt",
            "uuid": "{b73cb37c-40f2-493a-aaa9-41bc8d8974cc}",
            "type": "repository",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt"
                },
                "html": {
                    "href": "https://bitbucket.org/yt_analysis/yt"
                },
                "avatar": {
                    "href": "https://bitbucket.org/yt_analysis/yt/avatar/32/"
                }
            },
            "name": "yt"
        },
        "commit": {
            "hash": "ea182fc68fae",
            "links": {
                "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/yt_analysis/yt/commit/ea182fc68fae"
                }
            }
        },
        "branch": {
            "name": "yt-3.0"
        }
    }
}